import type { ElCssVarItem } from './types';

const colors: ElCssVarItem[] = [
  {
    type: 'primary',
    name: '品牌色',
    data: [
      {
        name: '主色调',
        depended: [
          'Badge',
          'Button',
          'Calendar',
          'CheckBox',
          'Selector',
          'Cascader',
          'Input',
          'Checkbox',
          'Collapse',
          'Select',
          'DatePicker',
          'Dialog',
          'Drawer',
          'Dropdown',
          'Link',
          'Loading',
          'Message',
          'Pagination',
          'Progress',
          'Radio',
          'Result',
          'Slider',
          'Step',
          'Switch',
          'Table',
          'Tabs',
          'Tag',
          'Text',
          'Timeline',
          'Transfer',
          'Tree',
          'Upload',
        ],
        value: '#409eff',
        originValue: '#409eff',
        darkOriginValue: '#409eff',
        id: 'elColorPrimart',
        cssVar: '--el-color-primary',
        type: 'color-16',
        unit: '',
        desc: '主背景色调，如Button等',
      },
      {
        name: '主色调亮3',
        depended: ['Link', 'Tag-dark'],
        value: '#79bbff',
        originValue: '#79bbff',
        darkOriginValue: '#3375b9',
        id: 'elColorPrimaryLight3',
        cssVar: '--el-color-primary-light-3',
        type: 'color-16',
        unit: '',
        desc: '主背景色调亮3',
      },
      {
        name: '主色调亮5',
        depended: ['Button', 'Link', 'Tag'],
        value: '#a0cfff',
        originValue: '#a0cfff',
        darkOriginValue: '#2a598a',
        id: 'elColorPrimaryLight5',
        cssVar: '--el-color-primary-light-5',
        type: 'color-16',
        unit: '',
        desc: '主背景色调亮5，如Button等',
      },
      {
        name: '主色调亮7',
        depended: ['Button', 'Checkbox'],
        value: '#c6e2ff',
        originValue: '#c6e2ff',
        darkOriginValue: '#213d5b',
        id: 'elColorPrimaryLight7',
        cssVar: '--el-color-primary-light-7',
        type: 'color-16',
        unit: '',
        desc: '主背景色调亮7，如Button等',
      },
      {
        name: '主色调亮8',
        depended: ['Button', 'Checkbox', 'Tag'],
        value: '#d9ecff',
        originValue: '#d9ecff',
        darkOriginValue: '#1d3043',
        id: 'elColorPrimaryLight8',
        cssVar: '--el-color-primary-light-8',
        type: 'color-16',
        unit: '',
        desc: '主背景色调亮8，如Button等',
      },
      {
        name: '主色调亮9',
        depended: ['Button', 'Calendar', 'Dropdown', 'Table', 'Tag', 'Tree', 'Upload'],
        value: '#ecf5ff',
        originValue: '#ecf5ff',
        darkOriginValue: '#18222b',
        id: 'elColorPrimaryLight9',
        cssVar: '--el-color-primary-light-9',
        type: 'color-16',
        unit: '',
        desc: '主背景色调亮9，如Button等',
      },
      {
        name: '主色调暗2',
        depended: ['Button'],
        value: '#337ecc',
        originValue: '#337ecc',
        darkOriginValue: '#66b1ff',
        id: 'elColorPrimaryDark2',
        cssVar: '--el-color-primary-dark-2',
        type: 'color-16',
        unit: '',
        desc: '主背景色调暗2',
      },
    ],
  },
  {
    type: 'success',
    name: '成功色',
    data: [
      {
        name: '成功色调',
        depended: [
          'Alert',
          'Badge',
          'Button',
          'Link',
          'Message',
          'Notification',
          'Progress',
          'Result',
          'Step',
          'Tag',
          'Text',
          'Timeline',
          'Upload',
        ],
        value: '#67c23a',
        originValue: '#67c23a',
        darkOriginValue: '#67c23a',
        id: 'elColorSuccess',
        cssVar: '--el-color-success',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调，如Button等',
      },
      {
        name: '成功色调亮3',
        depended: ['Button', 'Link', 'Tag'],
        value: '#95d475',
        originValue: '#95d475',
        darkOriginValue: '#4e8e2f',
        id: 'elColorSuccessLight3',
        cssVar: '--el-color-success-light-3',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调亮3，如Button等',
      },
      {
        name: '成功色调亮5',
        depended: ['Button', 'Link', 'Tag'],
        value: '#b3e19d',
        originValue: '#b3e19d',
        darkOriginValue: '#3e6b27',
        id: 'elColorSuccessLight5',
        cssVar: '--el-color-success-light-5',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调亮5，如Button等',
      },
      {
        name: '成功色调亮7',
        depended: [],
        value: '#d1edc4',
        originValue: '#d1edc4',
        darkOriginValue: '#2d481f',
        id: 'elColorSuccessLight7',
        cssVar: '--el-color-success-light-7',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调亮7，预留色',
      },
      {
        name: '成功色调亮8',
        depended: ['Button', 'Message', 'Tag'],
        value: '#e1f3d8',
        originValue: '#e1f3d8',
        darkOriginValue: '#25371c',
        id: 'elColorSuccessLight8',
        cssVar: '--el-color-success-light-8',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调亮8，如Button等',
      },
      {
        name: '成功色调亮9',
        depended: ['Alert', 'Button', 'Message', 'Tag'],
        value: '#f0f9eb',
        originValue: '#f0f9eb',
        darkOriginValue: '#1c2518',
        id: 'elColorSuccessLight9',
        cssVar: '--el-color-success-light-9',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调亮9，如Button等',
      },
      {
        name: '成功色调暗2',
        depended: ['Button'],
        value: '#529b2e',
        originValue: '#529b2e',
        darkOriginValue: '#85ce61',
        id: 'elColorSuccessDark2',
        cssVar: '--el-color-success-dark-2',
        type: 'color-16',
        unit: '',
        desc: '成功状态背景色调暗2，如Button等',
      },
    ],
  },
  {
    type: 'warning',
    name: '警告色',
    data: [
      {
        name: '警告色调',
        depended: [
          'Alert',
          'Button',
          'Badge',
          'Link',
          'Message',
          'Notification',
          'Progress',
          'Result',
          'Tag',
          'Text',
          'Timeline',
        ],
        value: '#e6a23c',
        originValue: '#e6a23c',
        darkOriginValue: '#e6a23c',
        id: 'elColorWarning',
        cssVar: '--el-color-warning',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调，如Button等',
      },
      {
        name: '警告色调亮3',
        depended: ['Link', 'Button', 'Tag'],
        value: '#eebe77',
        originValue: '#eebe77',
        darkOriginValue: '#a77730',
        id: 'elColorWarningLight3',
        cssVar: '--el-color-warning-light-3',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调亮3，如Button等',
      },
      {
        name: '警告色调亮5',
        depended: ['Link', 'Button', 'Tag'],
        value: '#f3d19e',
        originValue: '#f3d19e',
        darkOriginValue: '#7d5b28',
        id: 'elColorWarningLight5',
        cssVar: '--el-color-warning-light-5',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调亮5，如Button等',
      },
      {
        name: '警告色调亮7',
        depended: [],
        value: '#f8e3c5',
        originValue: '#f8e3c5',
        darkOriginValue: '#533f20',
        id: 'elColorWarningLight7',
        cssVar: '--el-color-warning-light-7',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调亮7，预留色',
      },
      {
        name: '警告色调亮8',
        depended: ['Message', 'Button', 'Tag'],
        value: '#faecd8',
        originValue: '#faecd8',
        darkOriginValue: '#3e301c',
        id: 'elColorWarningLight8',
        cssVar: '--el-color-warning-light-8',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调亮8，如Button等',
      },
      {
        name: '警告色调亮9',
        depended: ['Alert', 'Button', 'Message', 'Tag'],
        value: '#fdf6ec',
        originValue: '#fdf6ec',
        darkOriginValue: '#292218',
        id: 'elColorWarningLight9',
        cssVar: '--el-color-warning-light-9',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调亮9，如Button等',
      },
      {
        name: '警告色调暗2',
        depended: ['Button'],
        value: '#b88230',
        originValue: '#b88230',
        darkOriginValue: '#ebb563',
        id: 'elColorWarningDark2',
        cssVar: '--el-color-warning-dark-2',
        type: 'color-16',
        unit: '',
        desc: '警告状态背景色调暗2，如Button等',
      },
    ],
  },
  {
    type: 'danger',
    name: '危险色',
    data: [
      {
        name: '危险色调',
        depended: [
          'Badge',
          'Button',
          'Form',
          'Textarea',
          'Input',
          'Link',
          'Progress',
          'Result',
          'Step',
          'Tag',
          'Text',
          'Timeline',
        ],
        value: '#f56c6c',
        originValue: '#f56c6c',
        darkOriginValue: '#f56c6c',
        id: 'elColorDanger',
        cssVar: '--el-color-danger',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调，如Button等',
      },
      {
        name: '危险色调亮3',
        depended: ['Link', 'Button', 'Tag'],
        value: '#f89898',
        originValue: '#f89898',
        darkOriginValue: '#b25252',
        id: 'elColorDangerLight3',
        cssVar: '--el-color-danger-light-3',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调亮3，如Button等',
      },
      {
        name: '危险色调亮5',
        depended: ['Link', 'Button', 'Tag'],
        value: '#fab6b6',
        originValue: '#fab6b6',
        darkOriginValue: '#854040',
        id: 'elColorDangerLight5',
        cssVar: '--el-color-danger-light-5',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调亮5，如Button等',
      },
      {
        name: '危险色调亮7',
        depended: [],
        value: '#fcd3d3',
        originValue: '#fcd3d3',
        darkOriginValue: '#582e2e',
        id: 'elColorDangerLight7',
        cssVar: '--el-color-danger-light-7',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调亮7，预留色',
      },
      {
        name: '危险色调亮8',
        depended: ['Tag', 'Button'],
        value: '#fde2e2',
        originValue: '#fde2e2',
        darkOriginValue: '#412626',
        id: 'elColorDangerLight8',
        cssVar: '--el-color-danger-light-8',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调亮8，如Button等',
      },
      {
        name: '危险色调亮9',
        depended: ['Tag', 'Button'],
        value: '#fef0f0',
        originValue: '#fef0f0',
        darkOriginValue: '#2a1d1d',
        id: 'elColorDangerLight9',
        cssVar: '--el-color-danger-light-9',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调亮9，如Button等',
      },
      {
        name: '危险色调暗2',
        depended: ['Button'],
        value: '#c45656',
        originValue: '#c45656',
        darkOriginValue: '#f78989',
        id: 'elColorDangerDark2',
        cssVar: '--el-color-danger-dark-2',
        type: 'color-16',
        unit: '',
        desc: '危险状态背景色调暗2，如Button等',
      },
    ],
  },
  {
    type: 'error',
    name: '异常色',
    data: [
      {
        name: '错误色调',
        depended: ['Alert', 'Button', 'Link', 'Message', 'Notification', 'Result', 'Tag', 'Text'],
        value: '#f56c6c',
        originValue: '#f56c6c',
        darkOriginValue: '#f56c6c',
        id: 'elColorError',
        cssVar: '--el-color-error',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调，如Button等',
      },
      {
        name: '错误色调亮3',
        depended: ['Link', 'Tag'],
        value: '#f89898',
        originValue: '#f89898',
        darkOriginValue: '#b25252',
        id: 'elColorErrorLight3',
        cssVar: '--el-color-error-light-3',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调亮3',
      },
      {
        name: '错误色调亮5',
        depended: ['Link', 'Tag'],
        value: '#fab6b6',
        originValue: '#fab6b6',
        darkOriginValue: '#854040',
        id: 'elColorErrorLight5',
        cssVar: '--el-color-error-light-5',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调亮5',
      },
      {
        name: '错误色调亮7',
        depended: [],
        value: '#fcd3d3',
        originValue: '#fcd3d3',
        darkOriginValue: '#582e2e',
        id: 'elColorErrorLight7',
        cssVar: '--el-color-error-light-7',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调亮7，预留色',
      },
      {
        name: '错误色调亮8',
        depended: ['Message', 'Tag'],
        value: '#fde2e2',
        originValue: '#fde2e2',
        darkOriginValue: '#412626',
        id: 'elColorErrorLight8',
        cssVar: '--el-color-error-light-8',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调亮8',
      },
      {
        name: '错误色调亮9',
        depended: ['Alert', 'Message', 'Tag'],
        value: '#fef0f0',
        originValue: '#fef0f0',
        darkOriginValue: '#2a1d1d',
        id: 'elColorErrorLight9',
        cssVar: '--el-color-error-light-9',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调亮9',
      },
      {
        name: '错误色调暗2',
        depended: [],
        value: '#c45656',
        originValue: '#c45656',
        darkOriginValue: '#f78989',
        id: 'elColorErrorDark2',
        cssVar: '--el-color-error-dark-2',
        type: 'color-16',
        unit: '',
        desc: '错误状态背景色调暗2，预留色',
      },
    ],
  },
  {
    type: 'info',
    name: '信息色',
    data: [
      {
        name: '信息色调',
        depended: ['Alert', 'Button', 'Badge', 'CheckBox', 'Dialog', 'Textarea', 'Input', 'Link'],
        value: '#909399',
        originValue: '#909399',
        darkOriginValue: '#909399',
        id: 'elColorInfo',
        cssVar: '--el-color-info',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调，如Button等',
      },
      {
        name: '信息色调亮3',
        depended: ['Badge', 'Button', 'Calendar', 'CheckBox', 'Selector'],
        value: '#b1b3b8',
        originValue: '#b1b3b8',
        darkOriginValue: '#6b6d71',
        id: 'elColorInfoLight3',
        cssVar: '--el-color-info-light-3',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调亮3，如Button等',
      },
      {
        name: '信息色调亮5',
        depended: ['Badge', 'Button', 'Calendar', 'CheckBox', 'Selector'],
        value: '#c8c9cc',
        originValue: '#c8c9cc',
        darkOriginValue: '#525457',
        id: 'elColorInfoLight5',
        cssVar: '--el-color-info-light-5',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调亮5，如Button等',
      },
      {
        name: '信息色调亮7',
        depended: ['Badge', 'Button', 'Calendar', 'CheckBox', 'Selector'],
        value: '#dedfe0',
        originValue: '#dedfe0',
        darkOriginValue: '#393a3c',
        id: 'elColorInfoLight7',
        cssVar: '--el-color-info-light-7',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调亮7，如Button等',
      },
      {
        name: '信息色调亮8',
        depended: ['Badge', 'Button', 'Calendar', 'CheckBox', 'Selector'],
        value: '#e9e9eb',
        originValue: '#e9e9eb',
        darkOriginValue: '#2d2d2f',
        id: 'elColorInfoLight8',
        cssVar: '--el-color-info-light-8',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调亮8，如Button等',
      },
      {
        name: '信息色调亮9',
        depended: ['Badge', 'Button', 'Calendar', 'CheckBox', 'Selector'],
        value: '#f4f4f5',
        originValue: '#f4f4f5',
        darkOriginValue: '#202121',
        id: 'elColorInfoLight9',
        cssVar: '--el-color-info-light-9',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调亮9，如Button等',
      },
      {
        name: '信息色调暗2',
        depended: ['Badge', 'Button', 'Calendar', 'CheckBox', 'Selector'],
        value: '#73767a',
        originValue: '#73767a',
        darkOriginValue: '#a6a9ad',
        id: 'elColorInfoDark2',
        cssVar: '--el-color-info-dark-2',
        type: 'color-16',
        unit: '',
        desc: '信息状态背景色调暗2，如Button等',
      },
    ],
  },
  {
    type: 'bg',
    name: '背景色',
    data: [
      {
        name: '背景色',
        depended: ['全局'],
        value: '#ffffff',
        originValue: '#ffffff',
        darkOriginValue: '#141414',
        id: 'elBgColor',
        cssVar: '--el-bg-color',
        type: 'color-16',
        unit: '',
        desc: '全局背景色',
      },
      {
        name: '页面背景色',
        depended: ['全局'],
        value: '#f2f3f5',
        originValue: '#f2f3f5',
        darkOriginValue: '#0a0a0a',
        id: 'elBgColorPage',
        cssVar: '--el-bg-color-page',
        type: 'color-16',
        unit: '',
        desc: '页面背景色',
      },
      {
        name: '遮罩层背景色',
        depended: ['全局'],
        value: '#ffffff',
        originValue: '#ffffff',
        darkOriginValue: '#1d1e1f',
        id: 'elBgColorOverlay',
        cssVar: '--el-bg-color-overlay',
        type: 'color-16',
        unit: '',
        desc: '遮罩层背景色',
      },
    ],
  },
  {
    type: 'text',
    name: '文本色',
    data: [
      {
        name: '主要文本色',
        depended: ['全局'],
        value: '#303133',
        originValue: '#303133',
        darkOriginValue: '#e5eaf3',
        id: 'elTextColorPrimary',
        cssVar: '--el-text-color-primary',
        type: 'color-16',
        unit: '',
        desc: '主要文本色',
      },
      {
        name: '常规文本色',
        depended: ['全局'],
        value: '#606266',
        originValue: '#606266',
        darkOriginValue: '#cfd3dc',
        id: 'elTextColorRegular',
        cssVar: '--el-text-color-regular',
        type: 'color-16',
        unit: '',
        desc: '常规文本色',
      },
      {
        name: '次要文本色',
        depended: ['全局'],
        value: '#909399',
        originValue: '#909399',
        darkOriginValue: '#a3a6ad',
        id: 'elTextColorSecondary',
        cssVar: '--el-text-color-secondary',
        type: 'color-16',
        unit: '',
        desc: '次要文本色',
      },
      {
        name: '占位符文本色',
        depended: ['全局'],
        value: '#a8abb2',
        originValue: '#a8abb2',
        darkOriginValue: '#8d9095',
        id: 'elTextColorPlaceholder',
        cssVar: '--el-text-color-placeholder',
        type: 'color-16',
        unit: '',
        desc: '占位符文本色',
      },
      {
        name: '禁用文本色',
        depended: ['全局'],
        value: '#c0c4cc',
        originValue: '#c0c4cc',
        darkOriginValue: '#6c6e72',
        id: 'elTextColorDisabled',
        cssVar: '--el-text-color-disabled',
        type: 'color-16',
        unit: '',
        desc: '禁用文本色',
      },
    ],
  },
  {
    type: 'border',
    name: '边框色',
    data: [
      {
        name: '边框颜色',
        depended: ['全局'],
        value: '#dcdfe6',
        originValue: '#dcdfe6',
        darkOriginValue: '#4c4d4f',
        id: 'elBorderColor',
        cssVar: '--el-border-color',
        type: 'color-16',
        unit: '',
        desc: '常规边框颜色',
      },
      {
        name: '浅色边框颜色',
        depended: ['全局'],
        value: '#e4e7ed',
        originValue: '#e4e7ed',
        darkOriginValue: '#414243',
        id: 'elBorderColorLight',
        cssVar: '--el-border-color-light',
        type: 'color-16',
        unit: '',
        desc: '浅色边框颜色',
      },
      {
        name: '更浅色边框颜色',
        depended: ['全局'],
        value: '#ebeef5',
        originValue: '#ebeef5',
        darkOriginValue: '#363637',
        id: 'elBorderColorLighter',
        cssVar: '--el-border-color-lighter',
        type: 'color-16',
        unit: '',
        desc: '更浅色边框颜色',
      },
      {
        name: '极浅色边框颜色',
        depended: ['全局'],
        value: '#f2f6fc',
        originValue: '#f2f6fc',
        darkOriginValue: '#2b2b2c',
        id: 'elBorderColorExtraLight',
        cssVar: '--el-border-color-extra-light',
        type: 'color-16',
        unit: '',
        desc: '极浅色边框颜色',
      },
      {
        name: '深色边框颜色',
        depended: ['全局'],
        value: '#d4d7de',
        originValue: '#d4d7de',
        darkOriginValue: '#58585b',
        id: 'elBorderColorDark',
        cssVar: '--el-border-color-dark',
        type: 'color-16',
        unit: '',
        desc: '深色边框颜色',
      },
      {
        name: '更深色边框颜色',
        depended: ['全局'],
        value: '#cdd0d6',
        originValue: '#cdd0d6',
        darkOriginValue: '#636466',
        id: 'elBorderColorDarker',
        cssVar: '--el-border-color-darker',
        type: 'color-16',
        unit: '',
        desc: '更深色边框颜色',
      },
    ],
  },
  {
    type: 'fill',
    name: '填充色',
    data: [
      {
        name: '填充色',
        depended: ['全局'],
        value: '#f0f2f5',
        originValue: '#f0f2f5',
        darkOriginValue: '#303030',
        id: 'elFillColor',
        cssVar: '--el-fill-color',
        type: 'color-16',
        unit: '',
        desc: '常规填充色',
      },
      {
        name: '浅色填充色',
        depended: ['全局'],
        value: '#f5f7fa',
        originValue: '#f5f7fa',
        darkOriginValue: '#262727',
        id: 'elFillColorLight',
        cssVar: '--el-fill-color-light',
        type: 'color-16',
        unit: '',
        desc: '浅色填充色',
      },
      {
        name: '更浅色填充色',
        depended: ['全局'],
        value: '#fafafa',
        originValue: '#fafafa',
        darkOriginValue: '#1d1d1d',
        id: 'elFillColorLighter',
        cssVar: '--el-fill-color-lighter',
        type: 'color-16',
        unit: '',
        desc: '更浅色填充色',
      },
      {
        name: '极浅色填充色',
        depended: ['全局'],
        value: '#fafcff',
        originValue: '#fafcff',
        darkOriginValue: '#191919',
        id: 'elFillColorExtraLight',
        cssVar: '--el-fill-color-extra-light',
        type: 'color-16',
        unit: '',
        desc: '极浅色填充色',
      },
      {
        name: '深色填充色',
        depended: ['全局'],
        value: '#ebedf0',
        originValue: '#ebedf0',
        darkOriginValue: '#39393a',
        id: 'elFillColorDark',
        cssVar: '--el-fill-color-dark',
        type: 'color-16',
        unit: '',
        desc: '深色填充色',
      },
      {
        name: '更深色填充色',
        depended: ['全局'],
        value: '#e6e8eb',
        originValue: '#e6e8eb',
        darkOriginValue: '#424243',
        id: 'elFillColorDarker',
        cssVar: '--el-fill-color-darker',
        type: 'color-16',
        unit: '',
        desc: '更深色填充色',
      },
      {
        name: '空白填充色',
        depended: ['全局'],
        value: '#ffffff',
        originValue: '#ffffff',
        darkOriginValue: '#141414',
        id: 'elFillColorBlank',
        cssVar: '--el-fill-color-blank',
        type: 'color-16',
        unit: '',
        desc: '空白填充色',
      },
    ],
  },
  {
    type: 'mask',
    name: '遮罩色',
    data: [
      {
        name: '遮罩层颜色',
        depended: ['全局'],
        value: 'rgba(0, 0, 0, 0.8)',
        originValue: 'rgba(0, 0, 0, 0.8)',
        darkOriginValue: 'rgba(0, 0, 0, 0.8)',
        id: 'elOverlayColor',
        cssVar: '--el-overlay-color',
        type: 'color-rgba',
        unit: '',
        desc: '遮罩层颜色',
      },
      {
        name: '浅色遮罩层颜色',
        depended: ['全局'],
        value: 'rgba(0, 0, 0, 0.7)',
        originValue: 'rgba(0, 0, 0, 0.7)',
        darkOriginValue: 'rgba(0, 0, 0, 0.7)',
        id: 'elOverlayColorLight',
        cssVar: '--el-overlay-color-light',
        type: 'color-rgba',
        unit: '',
        desc: '浅色遮罩层颜色',
      },
      {
        name: '更浅色遮罩层颜色',
        depended: ['全局'],
        value: 'rgba(0, 0, 0, 0.5)',
        originValue: 'rgba(0, 0, 0, 0.5)',
        darkOriginValue: 'rgba(0, 0, 0, 0.5)',
        id: 'elOverlayColorLighter',
        cssVar: '--el-overlay-color-lighter',
        type: 'color-rgba',
        unit: '',
        desc: '更浅色遮罩层颜色',
      },
      {
        name: '遮罩颜色',
        depended: ['全局'],
        value: 'rgba(255, 255, 255, 0.9)',
        originValue: 'rgba(255, 255, 255, 0.9)',
        darkOriginValue: 'rgba(0, 0, 0, 0.8)',
        id: 'elMaskColor',
        cssVar: '--el-mask-color',
        type: 'color-rgba',
        unit: '',
        desc: '遮罩颜色',
      },
      {
        name: '极浅色遮罩颜色',
        depended: ['全局'],
        value: 'rgba(255, 255, 255, 0.3)',
        originValue: 'rgba(255, 255, 255, 0.3)',
        darkOriginValue: 'rgba(0, 0, 0, 0.3)',
        id: 'elMaskColorExtraLight',
        cssVar: '--el-mask-color-extra-light',
        type: 'color-rgba',
        unit: '',
        desc: '极浅色遮罩颜色',
      },
    ],
  },
];

const size: ElCssVarItem[] = [
  {
    type: 'fontSize',
    name: '字号',
    data: [
      {
        name: '超大字号',
        depended: [],
        value: 20,
        originValue: 20,
        darkOriginValue: 20,
        id: 'elFontSizeExtraLarge',
        cssVar: '--el-font-size-extra-large',
        type: 'fontSize',
        unit: 'px',
        desc: '超大字号',
      },
      {
        name: '大号字体',
        depended: [],
        value: 18,
        originValue: 18,
        darkOriginValue: 18,
        id: 'elFontSizeLarge',
        cssVar: '--el-font-size-large',
        type: 'fontSize',
        unit: 'px',
        desc: '大号字体',
      },
      {
        name: '中号字体',
        depended: [],
        value: 16,
        originValue: 16,
        darkOriginValue: 16,
        id: 'elFontSizeMedium',
        cssVar: '--el-font-size-medium',
        type: 'fontSize',
        unit: 'px',
        desc: '中号字体',
      },
      {
        name: '默认字号',
        depended: [],
        value: 14,
        originValue: 14,
        darkOriginValue: 14,
        id: 'elFontSizeBase',
        cssVar: '--el-font-size-base',
        type: 'fontSize',
        unit: 'px',
        desc: '默认字号',
      },
      {
        name: '小号字体',
        depended: [],
        value: 13,
        originValue: 13,
        darkOriginValue: 13,
        id: 'elFontSizeSmall',
        cssVar: '--el-font-size-small',
        type: 'fontSize',
        unit: 'px',
        desc: '小号字体',
      },
      {
        name: '超小字号',
        depended: [],
        value: 12,
        originValue: 12,
        darkOriginValue: 12,
        id: 'elFontSizeExtraSmall',
        cssVar: '--el-font-size-extra-small',
        type: 'fontSize',
        unit: 'px',
        desc: '超小字号',
      },
    ],
  },
  {
    type: 'lineHeight',
    name: '行间距',
    data: [
      {
        name: '大组件尺寸',
        depended: [],
        value: 40,
        originValue: 40,
        darkOriginValue: 40,
        id: 'elComponentSizeLarge',
        cssVar: '--el-component-size-large',
        type: 'lineHeight',
        unit: 'px',
        desc: '较大行间距/组件高度',
      },
      {
        name: '默认组件尺寸',
        depended: [],
        value: 32,
        originValue: 32,
        darkOriginValue: 32,
        id: 'elComponentSize',
        cssVar: '--el-component-size',
        type: 'lineHeight',
        unit: 'px',
        desc: '默认组件行间距/高度',
      },
      {
        name: '小型组件尺寸',
        depended: [],
        value: 24,
        originValue: 24,
        darkOriginValue: 24,
        id: 'elComponentSizeSmall',
        cssVar: '--el-component-size-small',
        type: 'lineHeight',
        unit: 'px',
        desc: '小型组件组件行间距/高度',
      },
      {
        name: '主要字体行高',
        depended: [],
        value: 24,
        originValue: 24,
        darkOriginValue: 24,
        id: 'elFontLineHeightPrimary',
        cssVar: '--el-font-line-height-primary',
        type: 'lineHeight',
        unit: 'px',
        desc: '主要字体行高',
      },
    ],
  },
  {
    type: 'fontWeight',
    name: '字体粗细',
    data: [
      {
        name: '主要字体粗细',
        depended: [],
        value: 500,
        originValue: 500,
        darkOriginValue: 500,
        id: 'elFontWeightPrimary',
        cssVar: '--el-font-weight-primary',
        type: 'fontWeight',
        unit: '',
        desc: '主要字体粗细',
      },
    ],
  },
];

const styles: ElCssVarItem[] = [
  {
    type: 'borderRadius',
    name: '圆角',
    data: [
      {
        name: '基础边框半径',
        depended: [],
        value: 4,
        originValue: 4,
        darkOriginValue: 4,
        id: 'elBorderRadiusBase',
        cssVar: '--el-border-radius-base',
        type: 'borderRadius',
        unit: 'px',
        desc: '基础边框半径',
      },
      {
        name: '小型边框半径',
        depended: [],
        value: 2,
        originValue: 2,
        darkOriginValue: 2,
        id: 'elBorderRadiusSmall',
        cssVar: '--el-border-radius-small',
        type: 'borderRadius',
        unit: 'px',
        desc: '小型边框半径',
      },
      {
        name: '圆形边框半径',
        depended: [],
        value: 0,
        originValue: 20,
        darkOriginValue: 20,
        id: 'elBorderRadiusRound',
        cssVar: '--el-border-radius-round',
        type: 'borderRadius',
        unit: 'px',
        desc: '圆形边框半径',
      },
      {
        name: '圆形边框半径',
        depended: [],
        value: 100,
        originValue: 100,
        darkOriginValue: 100,
        id: 'elBorderRadiusCircle',
        cssVar: '--el-border-radius-circle',
        type: 'borderRadius',
        unit: '%',
        desc: '圆形边框半径',
      },
    ],
  },
  {
    type: 'boxShadow',
    name: '阴影',
    data: [
      {
        name: '通用盒子阴影',
        depended: [],
        value: '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
        originValue: '0px 12px 32px 4px rgba(0, 0, 0, 0.04), 0px 8px 20px rgba(0, 0, 0, 0.08)',
        darkOriginValue: '0px 12px 32px 4px rgba(0, 0, 0, 0.36), 0px 8px 20px rgba(0, 0, 0, 0.72)',
        id: 'elBoxShadow',
        cssVar: '--el-box-shadow',
        type: 'boxShadow',
        unit: '',
        desc: '通用盒子阴影',
      },
      {
        name: '浅色盒子阴影',
        depended: [],
        value: '0px 0px 12px rgba(0, 0, 0, 0.12)',
        originValue: '0px 0px 12px rgba(0, 0, 0, 0.12)',
        darkOriginValue: '0px 0px 12px rgba(0, 0, 0, 0.72)',
        id: 'elBoxShadowLight',
        cssVar: '--el-box-shadow-light',
        type: 'boxShadow',
        unit: '',
        desc: '浅色盒子阴影',
      },
      {
        name: '较浅色盒子阴影',
        depended: [],
        value: '0px 0px 6px rgba(0, 0, 0, 0.12)',
        originValue: '0px 0px 6px rgba(0, 0, 0, 0.12)',
        darkOriginValue: '0px 0px 6px rgba(0, 0, 0, 0.72)',
        id: 'elBoxShadowLighter',
        cssVar: '--el-box-shadow-lighter',
        type: 'boxShadow',
        unit: '',
        desc: '较浅色盒子阴影',
      },
      {
        name: '深色盒子阴影',
        depended: [],
        value:
          '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12), 0px 8px 16px -8px rgba(0, 0, 0, 0.16)',
        originValue:
          '0px 16px 48px 16px rgba(0, 0, 0, 0.08), 0px 12px 32px rgba(0, 0, 0, 0.12), 0px 8px 16px -8px rgba(0, 0, 0, 0.16)',
        darkOriginValue: '0px 16px 48px 16px rgba(0, 0, 0, 0.72), 0px 12px 32px #000, 0px 8px 16px -8px #000',
        id: 'elBoxShadowDark',
        cssVar: '--el-box-shadow-dark',
        type: 'boxShadow',
        unit: '',
        desc: '深色盒子阴影',
      },
    ],
  },
];

const other: ElCssVarItem[] = [
  {
    type: 'border',
    name: '边框',
    data: [
      {
        name: '边框宽度',
        depended: ['全局'],
        value: 1,
        originValue: 1,
        darkOriginValue: 1,
        id: 'elBorderWidth',
        cssVar: '--el-border-width',
        type: 'borderWidth',
        unit: 'px',
        desc: '边框宽度',
      },
      {
        name: '边框样式',
        depended: ['全局'],
        value: 'solid',
        originValue: 'solid',
        darkOriginValue: 'solid',
        id: 'elBorderWidth',
        cssVar: '--el-border-style',
        type: 'borderStyle',
        unit: '',
        desc: '边框样式 支持solid 实线 dashed 虚线 dotted 点 none 无',
      },
    ],
  },
];

const backgroundImage =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAFpJREFUWAntljEKADAIA23p6v//qQ+wfUEcCu1yriEgp0FHRJSJcnehmmWm1Dv/lO4HIg1AAAKjTqm03ea88zMCCEDgO4HV5bS757f+7wRoAAIQ4B9gByAAgQ3pfiDmXmAeEwAAAABJRU5ErkJggg==';

export { colors, size, styles, other, backgroundImage };
