/** @type {import('cspell').CSpellSettings} */
export default {
  version: '0.2',
  language: 'en,en-US',
  allowCompoundWords: true,
  words: [
    'rubocop',
    'govet',
    'ehthumbs',
    'acmr',
    'antd',
    'antdv',
    'astro',
    'brotli',
    'clsx',
    'defu',
    'demi',
    'echarts',
    'ependencies',
    'esno',
    'etag',
    'execa',
    'iconify',
    'iconoir',
    'intlify',
    'lockb',
    'lucide',
    'minh',
    'minw',
    'mkdist',
    'mockjs',
    'naiveui',
    'nocheck',
    'noopener',
    'noreferrer',
    'nprogress',
    'nuxt',
    'pinia',
    'prefixs',
    'publint',
    'qrcode',
    'sonner',
    'sortablejs',
    'styl',
    'ui-kit',
    'uicons',
    'unplugin',
    'unref',
    'vite',
    'vitejs',
    'vitepress',
    'vnode',
    'vueuse',
  ],
  ignorePaths: [
    '**/node_modules/**',
    '**/dist/**',
    '**/icons/**',
    'package-lock.json',
    '**/*.log',
    '**/*.test.ts',
    '**/*.spec.ts',
    '**/__tests__/**',
    'package.tsbuildinfo',
    '.eslintcache',
    '.stylelintcache',
    '.gitignore',
    '.prettierignore',
    '.stylelintignore',
    '.vscode/*',
    'auto-imports.d.ts',
    'components.d.ts',
    '**/assets/**',
  ],
};
